### ISSUE TITLE
add integration tests

### ISSUE THREAD

**Issue by EduardSchwarzkopf** [aws-community-dach/event-system-frontend-web#17]
1. **Event Listing**: Test the `/events` GET endpoint to ensure it returns a list of all events as expected.

2. **Event Creation**: Test the `/events` POST endpoint to ensure it correctly creates a new event and returns the expected response.

3. **Event Retrieval**: Test the `/events/{eventID}` GET endpoint to ensure it returns the details of a specific event.

4. **Event Update**: Test the `/events/{eventID}` PUT endpoint to ensure it correctly updates an existing event and returns the updated event details.

5. **Event Deletion**: Test the `/events/{eventID}` DELETE endpoint to ensure it correctly deletes an existing event.

6. **Participant Listing**: Test the `/events/{eventID}/participants` GET endpoint to ensure it returns a list of all participants for a specific event.

7. **Participant Registration**: Test the `/events/{eventID}/participants` POST endpoint to ensure it correctly registers a participant for an event.

8. **Participant Retrieval**: Test the `/events/{eventID}/participants/{participantID}` GET endpoint to ensure it returns the details of a specific participant.

9. **Participant Update**: Test the `/events/{eventID}/participants/{participantID}` PUT endpoint to ensure it correctly updates participant details.

10. **Participant Deregistration**: Test the `/events/{eventID}/participants/{participantID}` DELETE endpoint to ensure it correctly deregisters a participant from an event.

**Comment by hoegertn** [comment]
Isn't this a backend task?

**Comment by EduardSchwarzkopf** [comment]
ah yes, you are right 🫣
